---

- name: make box black without a cat
  hosts: all
  become: yes
  handlers:
    - name: restart blackbox
      service:
        name: blackbox
        state: restarted
  tasks:
    - name: deploy blackbox executable
      copy:
        src: files/blackbox.py
        dest: /usr/local/bin/blackbox
        mode: 0755
      notify: restart blackbox

    - name: deploy blackbox service
      copy:
        src: files/blackbox.service
        dest: /etc/systemd/system/blackbox.service
      register: units

    - name: reload unit files
      shell: systemctl daemon-reload
      when: units | changed

    - name: ensure blackbox is up and running
      service:
        name: blackbox
        state: running
        enabled: yes

