# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.define vm_name = "blackbox" do |config|
    config.vm.hostname = vm_name
    #ip = "172.17.8.100"
    #config.vm.network :private_network, ip: ip
    config.vm.provision :ansible do |ansible|
      ansible.playbook = "blackify.yml"
      ansible.playbook = "fluentd.yml"
    end
  end
end
